name: Deploy HTML/CSS to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Add EC2 to known hosts to prevent host key verification issues
      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Step 3: Setup SSH for accessing the EC2 instance
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Deploy HTML/CSS to EC2
      - name: Deploy HTML/CSS to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
            # Navigate to the directory where the website is hosted
            cd /var/www/html
            # Pull the latest code from GitHub
            git pull origin main
            # Check Nginx status first
            sudo systemctl status nginx || echo "Nginx not running, trying to start it."
           
          ENDSSH
